### ISSUE TITLE
Add security to this architecture

### ISSUE THREAD

**Issue by mtabaj** [timwhit/enterprise-node-typescript#3]
Hi Tim,
Thanks for your work, I enjoyed it.
I want your opinion about what is the best way to add security in this architecture, for instance passport-jwt or equivalent.
Thanks in advance
Marcos

**Comment by pawlusmall** [comment]
I'm also interested on this.
Thanks for sharing.

**Comment by timwhit** [comment]
I'd try https://github.com/auth0/express-jwt first over passport-jwt. It would tie in better with express.js. Feel free to fork and PR this if you have time.
