### ISSUE TITLE
Supporting object relations during conversion between Address and AddressDTO

### ISSUE THREAD

**Issue by altocumulus** [timwhit/enterprise-node-typescript#5]
Hi Tim,
Although I know I am a bit late to the show I thought I'd give it a try and reach out to you for some advice as I read and re-read your article because I have found it to be really helpful. Thanks for that!

Your `AddressService` takes care of converting between `Address` and `AddressDTO` classes which looks alright in this simple example where you are dealing with flat objects. However, I cannot seem to find a decent approach when relations are involved. Suppose, e.g., a one-to-one relation between a user and an address:

```
export interface AddressDTO {
    _id?: string;
    address1: string;
    address2?: string;
    city: string;
    state: string;
    zip: string;
    country: string;
    user: UserDTO;   // 1:1 relation
}
```

How would you go about creating the `Address` object's `user` property from that DTO? Still in `AddressService`? Would you delegate to some other `UserService`? Would this still be feasible if there was an entire multi-layered tree of objects?

Any thoughts on this are highly appreciated.

**Comment by timwhit** [comment]
I would have the `AddressService` call the `UserService` and encapsulate all user related logic and transformation in the `UserService`. I wouldn't necessarily add the `UserDTO` to the `AddressDTO` however. I'd only add `user` to the `Address` domain object.

If this was split up into domain-driven microservices, you can imagine that the persistence layer for `Address` would not include the `User` as well.
